// Blueprint: auto-generated by Blueprint core
package main

import "container4/proc2"
import "sync"
import "log"

func main() {
	var nonleafService *proc2.NonLeafServiceImplHandler
	nonleafService = proc2.GetnonleafService()
	c := make(chan error, 1)
	wg_done := make(chan bool)
	var wg sync.WaitGroup
	wg.Add(1)
	go func(){
		defer wg.Done()
		err := proc2.RunnonleafService(nonleafService )
		if err != nil {
			c <- err
		}
	}()
	go func(){
		wg.Wait()
		wg_done <- true
	}()
	select {
	case err := <- c:
		log.Fatal(err)
	case <- wg_done:
		log.Println("Success")
	}

}
