// Blueprint: auto-generated by Blueprint core
package main

import "container3/proc1"
import "sync"
import "log"

func main() {
	var leafService *proc1.LeafServiceImplHandler
	leafService = proc1.GetleafService()
	c := make(chan error, 1)
	wg_done := make(chan bool)
	var wg sync.WaitGroup
	wg.Add(1)
	go func(){
		defer wg.Done()
		err := proc1.RunleafService(leafService )
		if err != nil {
			c <- err
		}
	}()
	go func(){
		wg.Wait()
		wg_done <- true
	}()
	select {
	case err := <- c:
		log.Fatal(err)
	case <- wg_done:
		log.Println("Success")
	}

}
