// Blueprint: auto-generated by Blueprint Core plugin
package proc2

import (
	"spec/services"
	"context"
)

type NonLeafServiceImpl struct {
	service *services.NonLeafServiceImpl
}
func NewNonLeafServiceImpl(handler *services.NonLeafServiceImpl) *NonLeafServiceImpl {
	return &NonLeafServiceImpl{service:handler}
}

func (this *NonLeafServiceImpl) Leaf(ctx context.Context, a int64) (int64, error) {
	return this.service.Leaf(ctx, a)
}

