// Blueprint: auto-generated by Blueprint Core plugin
package proc3

import (
	"context"
	"spec/services"
)

type LeafServiceImplClient struct {
	client *LeafServiceImplClientpool
}
func NewLeafServiceImplClient(client *LeafServiceImplClientpool) *LeafServiceImplClient {
	return &LeafServiceImplClient{client:client}
}

func (this *LeafServiceImplClient) Object(ctx context.Context, obj services.LeafObject) (services.LeafObject, error) {
	return this.client.Object(ctx, obj)
}

func (this *LeafServiceImplClient) Leaf(ctx context.Context, a int64) (int64, error) {
	return this.client.Leaf(ctx, a)
}

