// Blueprint: auto-generated by HealthCheck plugin
package proc3

import (
	"context"
)

type WebServiceImplHealthChecker struct {
	service *WebServiceImplTracer
}
func NewWebServiceImplHealthChecker(service *WebServiceImplTracer) *WebServiceImplHealthChecker {
	return &WebServiceImplHealthChecker{service: service}
}

func (hc *WebServiceImplHealthChecker) Leaf(ctx context.Context, a int64, jaegerTracer_trace_ctx string) (int64, error) {
	return hc.service.Leaf(ctx, a, jaegerTracer_trace_ctx)
	
}

func (hc *WebServiceImplHealthChecker) Hello(ctx context.Context, world string, jaegerTracer_trace_ctx string) (string, error) {
	return hc.service.Hello(ctx, world, jaegerTracer_trace_ctx)
	
}

func (hc *WebServiceImplHealthChecker) Health(ctx context.Context) (string, error) {
	return "Healthy", nil
}

