version: '3'
services:
  container1:
    image: jaegertracing/all-in-one:latest
    hostname: jaegerTracer
    ports:
      - "6831:6831"
      - "5778:5778"
      - "14268:14268"
      - "6832:6832"
      - "16686:16686"
      - "5775:5775"
    environment:
      - jaegerTracer_ADDRESS=jaegerTracer
      - jaegerTracer_PORT=14268
    restart: always

  container2:
    image: jonathanmace/xtrace-server:latest
    hostname: xtrace-server
    ports:
      - "4080:4080"
      - "5563:5563"
    environment:
      - xtracer_ADDRESS=xtrace-server
      - xtracer_PORT=5563
    restart: always

  container3:
    build:
      context: .
      dockerfile: ./container3/docker/Dockerfile
    hostname: leafService
    ports:
      - "9500:9500"
    environment:
      - jaegerTracer_ADDRESS=jaegerTracer
      - jaegerTracer_PORT=14268
      - leafService_ADDRESS=leafService
      - leafService_PORT=9500
    restart: always

  container4:
    build:
      context: .
      dockerfile: ./container4/docker/Dockerfile
    hostname: nonleafService
    ports:
      - "9501:9501"
    environment:
      - leafService_PORT=9500
      - nonleafService_ADDRESS=nonleafService
      - nonleafService_PORT=9501
      - jaegerTracer_ADDRESS=jaegerTracer
      - jaegerTracer_PORT=14268
      - leafService_ADDRESS=leafService
    restart: always

  container5:
    build:
      context: .
      dockerfile: ./container5/docker/Dockerfile
    hostname: webService
    ports:
      - "9502:9502"
    environment:
      - webService_ADDRESS=webService
      - webService_PORT=9502
      - jaegerTracer_ADDRESS=jaegerTracer
      - jaegerTracer_PORT=14268
      - leafService_ADDRESS=leafService
      - leafService_PORT=9500
    restart: always

