// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: leaf.proto

package leaf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeafObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *LeafObject) Reset() {
	*x = LeafObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafObject) ProtoMessage() {}

func (x *LeafObject) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafObject.ProtoReflect.Descriptor instead.
func (*LeafObject) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{0}
}

func (x *LeafObject) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *LeafObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LeafServiceImpl_LeafResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetVal0 int64 `protobuf:"varint,1,opt,name=RetVal0,proto3" json:"RetVal0,omitempty"`
}

func (x *LeafServiceImpl_LeafResponse) Reset() {
	*x = LeafServiceImpl_LeafResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafServiceImpl_LeafResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafServiceImpl_LeafResponse) ProtoMessage() {}

func (x *LeafServiceImpl_LeafResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafServiceImpl_LeafResponse.ProtoReflect.Descriptor instead.
func (*LeafServiceImpl_LeafResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{1}
}

func (x *LeafServiceImpl_LeafResponse) GetRetVal0() int64 {
	if x != nil {
		return x.RetVal0
	}
	return 0
}

type LeafServiceImpl_ObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetVal0 *LeafObject `protobuf:"bytes,1,opt,name=RetVal0,proto3" json:"RetVal0,omitempty"`
}

func (x *LeafServiceImpl_ObjectResponse) Reset() {
	*x = LeafServiceImpl_ObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafServiceImpl_ObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafServiceImpl_ObjectResponse) ProtoMessage() {}

func (x *LeafServiceImpl_ObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafServiceImpl_ObjectResponse.ProtoReflect.Descriptor instead.
func (*LeafServiceImpl_ObjectResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{2}
}

func (x *LeafServiceImpl_ObjectResponse) GetRetVal0() *LeafObject {
	if x != nil {
		return x.RetVal0
	}
	return nil
}

type NonLeafServiceImpl_LeafResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetVal0 int64 `protobuf:"varint,1,opt,name=RetVal0,proto3" json:"RetVal0,omitempty"`
}

func (x *NonLeafServiceImpl_LeafResponse) Reset() {
	*x = NonLeafServiceImpl_LeafResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonLeafServiceImpl_LeafResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonLeafServiceImpl_LeafResponse) ProtoMessage() {}

func (x *NonLeafServiceImpl_LeafResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonLeafServiceImpl_LeafResponse.ProtoReflect.Descriptor instead.
func (*NonLeafServiceImpl_LeafResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{3}
}

func (x *NonLeafServiceImpl_LeafResponse) GetRetVal0() int64 {
	if x != nil {
		return x.RetVal0
	}
	return 0
}

type LeafServiceImpl_LeafRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A                    int64  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	JaegerTracerTraceCtx string `protobuf:"bytes,2,opt,name=jaegerTracer_trace_ctx,json=jaegerTracerTraceCtx,proto3" json:"jaegerTracer_trace_ctx,omitempty"`
}

func (x *LeafServiceImpl_LeafRequest) Reset() {
	*x = LeafServiceImpl_LeafRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafServiceImpl_LeafRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafServiceImpl_LeafRequest) ProtoMessage() {}

func (x *LeafServiceImpl_LeafRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafServiceImpl_LeafRequest.ProtoReflect.Descriptor instead.
func (*LeafServiceImpl_LeafRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{4}
}

func (x *LeafServiceImpl_LeafRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *LeafServiceImpl_LeafRequest) GetJaegerTracerTraceCtx() string {
	if x != nil {
		return x.JaegerTracerTraceCtx
	}
	return ""
}

type LeafServiceImpl_ObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Obj                  *LeafObject `protobuf:"bytes,1,opt,name=obj,proto3" json:"obj,omitempty"`
	JaegerTracerTraceCtx string      `protobuf:"bytes,2,opt,name=jaegerTracer_trace_ctx,json=jaegerTracerTraceCtx,proto3" json:"jaegerTracer_trace_ctx,omitempty"`
}

func (x *LeafServiceImpl_ObjectRequest) Reset() {
	*x = LeafServiceImpl_ObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafServiceImpl_ObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafServiceImpl_ObjectRequest) ProtoMessage() {}

func (x *LeafServiceImpl_ObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafServiceImpl_ObjectRequest.ProtoReflect.Descriptor instead.
func (*LeafServiceImpl_ObjectRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{5}
}

func (x *LeafServiceImpl_ObjectRequest) GetObj() *LeafObject {
	if x != nil {
		return x.Obj
	}
	return nil
}

func (x *LeafServiceImpl_ObjectRequest) GetJaegerTracerTraceCtx() string {
	if x != nil {
		return x.JaegerTracerTraceCtx
	}
	return ""
}

type NonLeafServiceImpl_LeafRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A                    int64  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	JaegerTracerTraceCtx string `protobuf:"bytes,2,opt,name=jaegerTracer_trace_ctx,json=jaegerTracerTraceCtx,proto3" json:"jaegerTracer_trace_ctx,omitempty"`
}

func (x *NonLeafServiceImpl_LeafRequest) Reset() {
	*x = NonLeafServiceImpl_LeafRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonLeafServiceImpl_LeafRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonLeafServiceImpl_LeafRequest) ProtoMessage() {}

func (x *NonLeafServiceImpl_LeafRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonLeafServiceImpl_LeafRequest.ProtoReflect.Descriptor instead.
func (*NonLeafServiceImpl_LeafRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{6}
}

func (x *NonLeafServiceImpl_LeafRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *NonLeafServiceImpl_LeafRequest) GetJaegerTracerTraceCtx() string {
	if x != nil {
		return x.JaegerTracerTraceCtx
	}
	return ""
}

var File_leaf_proto protoreflect.FileDescriptor

var file_leaf_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x65,
	0x61, 0x66, 0x22, 0x30, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x66, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x1c, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6d, 0x70, 0x6c, 0x5f, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x30, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x52, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x30, 0x22, 0x4c,
	0x0a, 0x1e, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70,
	0x6c, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x07, 0x52, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x30, 0x22, 0x3b, 0x0a, 0x1f,
	0x4e, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d,
	0x70, 0x6c, 0x5f, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x52, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x30, 0x22, 0x61, 0x0a, 0x1b, 0x4c, 0x65, 0x61,
	0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70, 0x6c, 0x5f, 0x4c, 0x65, 0x61,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x12, 0x34, 0x0a, 0x16, 0x6a, 0x61, 0x65, 0x67, 0x65, 0x72,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x74, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x6a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x54, 0x72,
	0x61, 0x63, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x74, 0x78, 0x22, 0x79, 0x0a, 0x1d,
	0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70, 0x6c, 0x5f,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x03, 0x6f, 0x62, 0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x65, 0x61,
	0x66, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x03, 0x6f, 0x62,
	0x6a, 0x12, 0x34, 0x0a, 0x16, 0x6a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x65,
	0x72, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x74, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x6a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x65, 0x72, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x43, 0x74, 0x78, 0x22, 0x64, 0x0a, 0x1e, 0x4e, 0x6f, 0x6e, 0x4c, 0x65,
	0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70, 0x6c, 0x5f, 0x4c, 0x65,
	0x61, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x12, 0x34, 0x0a, 0x16, 0x6a, 0x61, 0x65, 0x67, 0x65,
	0x72, 0x54, 0x72, 0x61, 0x63, 0x65, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x74,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x6a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x74, 0x78, 0x32, 0xb9, 0x01,
	0x0a, 0x0f, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70,
	0x6c, 0x12, 0x4f, 0x0a, 0x04, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x21, 0x2e, 0x6c, 0x65, 0x61, 0x66,
	0x2e, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70, 0x6c,
	0x5f, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6c,
	0x65, 0x61, 0x66, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6d, 0x70, 0x6c, 0x5f, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x55, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x23, 0x2e, 0x6c,
	0x65, 0x61, 0x66, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6d, 0x70, 0x6c, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70, 0x6c, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x6b, 0x0a, 0x12, 0x4e, 0x6f, 0x6e,
	0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70, 0x6c, 0x12,
	0x55, 0x0a, 0x04, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x24, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x4e,
	0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6d, 0x70,
	0x6c, 0x5f, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x6c, 0x65, 0x61, 0x66, 0x2e, 0x4e, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x66, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6d, 0x70, 0x6c, 0x5f, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f,
	0x2f, 0x6c, 0x65, 0x61, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_leaf_proto_rawDescOnce sync.Once
	file_leaf_proto_rawDescData = file_leaf_proto_rawDesc
)

func file_leaf_proto_rawDescGZIP() []byte {
	file_leaf_proto_rawDescOnce.Do(func() {
		file_leaf_proto_rawDescData = protoimpl.X.CompressGZIP(file_leaf_proto_rawDescData)
	})
	return file_leaf_proto_rawDescData
}

var file_leaf_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_leaf_proto_goTypes = []interface{}{
	(*LeafObject)(nil),                      // 0: leaf.LeafObject
	(*LeafServiceImpl_LeafResponse)(nil),    // 1: leaf.LeafServiceImpl_LeafResponse
	(*LeafServiceImpl_ObjectResponse)(nil),  // 2: leaf.LeafServiceImpl_ObjectResponse
	(*NonLeafServiceImpl_LeafResponse)(nil), // 3: leaf.NonLeafServiceImpl_LeafResponse
	(*LeafServiceImpl_LeafRequest)(nil),     // 4: leaf.LeafServiceImpl_LeafRequest
	(*LeafServiceImpl_ObjectRequest)(nil),   // 5: leaf.LeafServiceImpl_ObjectRequest
	(*NonLeafServiceImpl_LeafRequest)(nil),  // 6: leaf.NonLeafServiceImpl_LeafRequest
}
var file_leaf_proto_depIdxs = []int32{
	0, // 0: leaf.LeafServiceImpl_ObjectResponse.RetVal0:type_name -> leaf.LeafObject
	0, // 1: leaf.LeafServiceImpl_ObjectRequest.obj:type_name -> leaf.LeafObject
	4, // 2: leaf.LeafServiceImpl.Leaf:input_type -> leaf.LeafServiceImpl_LeafRequest
	5, // 3: leaf.LeafServiceImpl.Object:input_type -> leaf.LeafServiceImpl_ObjectRequest
	6, // 4: leaf.NonLeafServiceImpl.Leaf:input_type -> leaf.NonLeafServiceImpl_LeafRequest
	1, // 5: leaf.LeafServiceImpl.Leaf:output_type -> leaf.LeafServiceImpl_LeafResponse
	2, // 6: leaf.LeafServiceImpl.Object:output_type -> leaf.LeafServiceImpl_ObjectResponse
	3, // 7: leaf.NonLeafServiceImpl.Leaf:output_type -> leaf.NonLeafServiceImpl_LeafResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_leaf_proto_init() }
func file_leaf_proto_init() {
	if File_leaf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_leaf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafServiceImpl_LeafResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafServiceImpl_ObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonLeafServiceImpl_LeafResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafServiceImpl_LeafRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafServiceImpl_ObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonLeafServiceImpl_LeafRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leaf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_leaf_proto_goTypes,
		DependencyIndexes: file_leaf_proto_depIdxs,
		MessageInfos:      file_leaf_proto_msgTypes,
	}.Build()
	File_leaf_proto = out.File
	file_leaf_proto_rawDesc = nil
	file_leaf_proto_goTypes = nil
	file_leaf_proto_depIdxs = nil
}
