// Blueprint: auto-generated by Blueprint Core
package proc1

import "spec/services"
func GetleafService() *LeafServiceImplHandler {
	jaegertracer := NewjaegerTracer()
	spec_handler := services.NewLeafServiceImpl()
	leafserviceimpl := NewLeafServiceImpl(spec_handler)
	leafserviceimpltracer := NewLeafServiceImplTracer(leafserviceimpl, jaegertracer, "LeafService", "1")
	leafserviceimplhandler := NewLeafServiceImplHandler(leafserviceimpltracer, "grpc", "1s")
	return leafserviceimplhandler
}

func RunleafService(service *LeafServiceImplHandler) error{
return service.Run()
}

